language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-6
            - clang-5.0
matrix:
    include:
        - os: linux
          env: CXX_COMPILER=clang++-5.0
        - os: linux
          env: CXX_COMPILER=g++-6
        - os: osx
          osx_image: xcode8.3
          env: CXX_COMPILER=clang++

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=DEBUG                                               \
          -D frozen.coverage=ON                                                   \
          -D CMAKE_CXX_COMPILER=${CXX_COMPILER}                                   \
	  -D CMAKE_VERBOSE_MAKEFILE=ON                                            \
	  -D CTEST_DROP_SITE_CDASH=TRUE                                           \
	  -D CTEST_DROP_METHOD="http"                                             \
	  -D CTEST_DROP_SITE="my.cdash.org"                                       \
	  -D CTEST_DROP_LOCATION="/submit.php?project=frozen"                     \
	  -D BUILDNAME="$(uname -s)-${CXX_COMPILER}-$(data +'%Y-%m-%d-%H:%M:%S')" \
	  ..
  - ctest -VV -M Experimental -T Start \
    && ctest -VV -M Experimental -T Build \
    && ctest -VV -M Experimental -T Test \
    && ctest -VV -M Experimental -T Coverage    
  - ctest -VV -M Experimental -T Submit
  

